version: 1.0.{build}
image: Visual Studio 2015
init:
- ps: $env:Path += ";" + (Join-Path $env:USERPROFILE ".cargo/bin")
- ps: $env:RUSTUP_HOME = (Join-Path $env:USERPROFILE ".rustup")
- ps: $env:CARGO_HOME = (Join-Path $env:USERPROFILE ".cargo")

before_build:
- ps: Write-Host $env:Path
- ps: Write-Host $env:RUSTUP_HOME
- ps: Write-Host $env:CARGO_HOME

build_script:
- ps: ./build/build.ps1 -target Build